# Generated by Django 3.2.8 on 2021-11-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Язык Программирования')),
                ('slug', models.CharField(blank=True, max_length=50, unique=True, verbose_name='SLUG')),
            ],
            options={
                'verbose_name': 'Язык Программирования',
                'verbose_name_plural': 'Языки Программирования',
            },
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='SLUG'),
        ),
    ]
